09.Test/Monthly/9/[12기_3회차] 월말평가_파이썬 트랙_Debugging_problem/buckets/urls.py
from django.urls import path
from . import views

app_name = 'buckets'
urlpatterns = [
    path('', views.index, name='index',),
    path('about/', views.about, name='about',),
    path('<int:bucket_pk>/', views.detail, name='detail',),
    path('create/', views.create, name='create'),
    path('<int:bucket_pk>/update/', views.update, name='update'),
    path('<int:bucket_pk>/delete/', views.delete, name='delete'),
]

09.Test/Monthly/9/[12기_3회차] 월말평가_파이썬 트랙_Debugging_problem/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# URL Configuration
urlpatterns = [
    path('admin/', admin.site.urls),
    path('bucket/', include('buckets.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

09.Test/Monthly/9/[12기_3회차] 월말평가_파이썬 트랙_Debugging_problem/buckets/models.py
from django.db import models


class TravelBucketList(models.Model):
    # 고유 식별자 (Primary Key)는 Django가 자동으로 'id' 필드를 생성해줌
    destination_name = models.CharField(max_length=255)
    country = models.CharField(max_length=100)
    city = models.CharField(max_length=100, null=True, blank=True)
    image = models.ImageField(blank=True)
    reason = models.TextField(null=True, blank=True)
    planned_visit_date = models.DateField(null=True, blank=True)

    PRIORITY_CHOICES = [
        (1, 'High'),
        (2, 'Medium'),
        (3, 'Low'),
    ]

    priority = models.PositiveSmallIntegerField(choices=PRIORITY_CHOICES, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.destination_name

09.Test/Monthly/9/[12기_3회차] 월말평가_파이썬 트랙_Debugging_problem/buckets/forms.py
from django import forms
from .models import TravelBucketList


class TravelBucketListForm(forms.ModelForm):
    class Meta:
        model = TravelBucketList
        fields = '__all__'
        widgets = {
            'destination_name': forms.TextInput(attrs={'class': 'form-control'}),
            'country': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
            'reason': forms.Textarea(attrs={'class': 'form-control'}),
            'planned_visit_date': forms.DateInput(attrs={'class': 'form-control'}),
            'priority': forms.Select(attrs={'class': 'form-control'}),
        }

09.Test/Monthly/9/[12기_3회차] 월말평가_파이썬 트랙_Debugging_problem/buckets/views.py
from django.shortcuts import render, redirect
from .models import TravelBucketList
from .forms import TravelBucketListForm


# Create your views here.

def index(request):
    travel_bucket_lists = TravelBucketList.objects.all()
    context = {
        'travel_bucket_lists': travel_bucket_lists
    }
    return render(request, 'buckets/index.html', context)


def about(request):
    return render(request, 'buckets/about.html')


def detail(request, bucket_pk):
    bucket_item = TravelBucketList.objects.get(pk=bucket_pk)
    context = {
        'bucket_item': bucket_item
    }
    return render(request, 'buckets/detail.html', context)


def create(request):
    if request.method == 'POST':
        form = TravelBucketListForm(request.POST, request.FILES)
        if form.is_valid():
            travel_bucket_list_item = form.save()
            return redirect('buckets:detail', travel_bucket_list_item.pk)
    else:
        form = TravelBucketListForm()
        
    context = {
        'form': form
    }
    return render(request, 'buckets/create.html', context)


def update(request, bucket_pk):
    bucket_item = TravelBucketList.objects.get(pk=bucket_pk)
    if request.method == 'POST':
        form = TravelBucketListForm(request.POST, request.FILES)
        if form.is_valid():
            travel_bucket_list_item = form.save()
            return redirect('buckets:detail', travel_bucket_list_item.pk)
    else:
        form = TravelBucketListForm(instance=bucket_item)
    context = {
        'bucket_item': bucket_item,
        'form': form
    }
    return render(request, 'buckets/update.html', context)


def delete(request, bucket_pk):
    bucket_item = TravelBucketList.objects.get(pk=bucket_pk)
    if request.method == 'POST':
        bucket_item.delete()
        form = TravelBucketListForm(request.POST, request.FILES)
        if form.is_valid():
            travel_bucket_list_item = form.save()
        
    return redirect('buckets:detail', travel_bucket_list_item.pk)

09.Test/Monthly/9/[12기_3회차] 월말평가_파이썬 트랙_Debugging_problem/buckets/templates/buckets/about.html
{% comment %} extends가 맨 위에 오도록 수정 {% endcomment %}
{% extends 'base.html' %}
{% load static %}
{% comment %} block의 이름을 base의 block과 같도록 수정 {% endcomment %}
{% block  content %}
  <h1>여행지 버킷리스트</h1>
  <p>이 사이트는 여행지 버킷리스트를 만들어보는 사이트입니다.</p>
  <p>여행지 버킷리스트를 만들어보세요.</p>
  <img src="{% static 'assets/flight01.jpg' %}"
       alt="noimage"
       style="max-width: 500px;
              max-height:500px">
{% endblock content %}

09.Test/Monthly/9/[12기_3회차] 월말평가_파이썬 트랙_Debugging_problem/buckets/templates/buckets/create.html
{% extends 'base.html' %}

{% block content %}
    <h1>새로운 여행지 버킷리스트 작성</h1>

  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary">[CREATE]</button>
  </form>
  <a href="{% url 'buckets:index' %}">[BACK]</a>
{% endblock content %}

09.Test/Monthly/9/[12기_3회차] 월말평가_파이썬 트랙_Debugging_problem/buckets/templates/buckets/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <h1>여행지 버킷리스트</h1>
  <p>
    <span>{{ bucket_item.pk }}번 여행지 |</span> {{ bucket_item.destination_name }}
  </p>
  <p>작성 시간 : {{ bucket_item.created_at }}</p>
  <hr>
  {% if bucket_item.image %}
    <img src="{{ bucket_item.image.url }}"
         alt="{{ bucket_item.image_description }}">
  {% else %}
    <img src="{% static 'assets/noimage.png' %}"
         alt="noimage"
         style="max-width: 200px;
                max-height:200px">
  {% endif %}
  <p>{{ bucket_item.content }}</p>
  <hr>
  <a href="{% url 'buckets:update' bucket_item.pk %}">[UPDATE]</a>
  <form action="{% url 'buckets:delete' bucket_item.pk %}" method="POST">
    {% csrf_token %}
    <button class="btn btn-danger">[DELETE]</button>
  </form>
  <a href="{% url 'buckets:index' %}">[BACK]</a>
{% endblock content %}

09.Test/Monthly/9/[12기_3회차] 월말평가_파이썬 트랙_Debugging_problem/buckets/templates/buckets/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <h1>여행지 버킷리스트 서비스</h1>
  <a href="{% url 'buckets:create' %}">[CREATE]</a>
  <ul>
    {% for list in travel_bucket_lists %}
      <a href="{% url 'buckets:detail' list.pk %}">
        {% if list.image %}
          <img src="{{ list.image.url }}" alt="{{ list.image_description }}">
          {% comment %} 이미지가 없을 때 static/assets 안의 noimage를 불러오도록 수정 {% endcomment %}
        {% else %}
          <img src="{% static 'assets/noimage.png' %}"
               alt="noimage"
               style="max-width: 200px;
                      max-height:200px">
        {% endif %}
        {% comment %} 목적지 이름을 제대로 반환하도록 수정 {% endcomment %}
        <p>{{ list.destination_name }}</p>
      </a>
      <hr>
    {% endfor %}
  </ul>
{% endblock content %}

09.Test/Monthly/9/[12기_3회차] 월말평가_파이썬 트랙_Debugging_problem/buckets/templates/buckets/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>버킷 리스트 수정</h1>

  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-warning">[UPDATE]</button>
  </form>
  <a href="{% url 'buckets:detail' bucket_item.pk %}">[BACK]</a>
{% endblock content %}

09.Test/Monthly/9/[12기_3회차] 월말평가_파이썬 트랙_Debugging_problem/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'assets/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'buckets:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'buckets:about' %}">About</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
  <div class="container">


    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>